name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  # Test Job: Runs unit tests, static analysis, code quality checks, and performance tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Run Unit Tests with Coverage
        run: go test -cover ./...

      - name: Run Staticcheck for Static Analysis
        run: staticcheck ./...

      - name: Run Performance Tests
        run: go test -bench .  # Run Go benchmarks

  # Build Job: Builds the Go application
  build:
    runs-on: ubuntu-latest
    needs: test  # Ensure this job runs only after tests are successful
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Build Go application
        run: go build -o go-web-app

  # Docker Image Build and Push Job
  push:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs only after the build job completes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/go-web-app:${{ github.run_id }}

  # Update Helm Chart with New Tag Job
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push  # Ensure this job runs only after the push job completes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's|tag: .*|tag: "${{ github.run_id }}"|' helm/go-web-app-chart/values.yaml
          sed -i 's|repository: .*|repository: ${{ secrets.ACR_LOGIN_SERVER }}/go-web-app|' helm/go-web-app-chart/values.yaml

      - name: Commit and push changes to Helm chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "lingammani2@gmail.com"
          git config --global user.name "rushimanikantalingam"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update tag and repository in Helm chart"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
