name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Go 1.22
      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      # Build the application
      - name: Build Go application
        run: go build -o go-web-app

      # Run tests
      - name: Run Go tests
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run golangci-lint
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: v1.56.2
          args: --timeout=5m

  push:
    runs-on: ubuntu-latest
    needs: [build, code-quality]
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push Docker image to ACR
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/go-web-app:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Update tag and repository in Helm chart
      - name: Update tag in Helm chart
        run: |
          sed -i 's|tag: .*|tag: "${{ github.run_id }}"|' helm/go-web-app-chart/values.yaml
          sed -i 's|repository: .*|repository: ${{ secrets.ACR_LOGIN_SERVER }}/go-web-app|' helm/go-web-app-chart/values.yaml

      # Commit and push changes to GitHub repository
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "lingammani2@gmail.com"
          git config --global user.name "rushimanikantalingam"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update tag and repository in Helm chart"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
