name: CDK8s Synth to Helm (TypeScript)

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  synth-and-copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install CDK8s CLI and dependencies
        run: |
          npm install -g cdk8s-cli
          cd go-web-app/cdk8s-go-web
          npm install

      - name: Synthesize Kubernetes manifests
        run: |
          cd go-web-app/cdk8s-go-web
          cdk8s synth --output temp-synth-output

      - name: Copy synthesized YAML to Helm chart templates
        run: |
          mkdir -p helm/go-web-app-chart/templates/generated
          cp go-web-app/cdk8s-go-web/temp-synth-output/*.k8s.yaml helm/go-web-app-chart/templates/generated/
