name: CDK8s Synth to Helm (TypeScript, No Local Setup)

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  synth-and-copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up CDK8s environment, compile, and synth
        run: |
          cd cdk8s-go-web

          # Initialize Node.js project
          npm init -y

          # Install CDK8s dependencies
          npm install cdk8s constructs typescript cdk8s-plus-25

          # Install CDK8s CLI globally
          npm install -g cdk8s-cli

          # Create TypeScript config (recursive include)
          cat <<EOF > tsconfig.json
          {
            "compilerOptions": {
              "target": "ES2020",
              "module": "CommonJS",
              "outDir": "dist",
              "strict": true
            },
            "include": ["**/*.ts"]
          }
          EOF

          # Create main.ts file with resources (Deployment, Service, Ingress)
          cat <<EOF > main.ts
          import { App, Chart } from 'cdk8s';
          import { Construct } from 'constructs';
          import * as k8s from 'cdk8s-plus-25';

          class MyChart extends Chart {
            constructor(scope: Construct, id: string) {
              super(scope, id);

              // Create Deployment
              new k8s.Deployment(this, 'web-deployment', {
                metadata: { name: 'web' },
                containers: [{ image: 'nginx' }],
              });

              // Create Service
              new k8s.Service(this, 'web-service', {
                metadata: { name: 'web-service' },
                spec: {
                  ports: [{ port: 80 }],
                  selector: { app: 'web' },
                },
              });

              // Create Ingress
              new k8s.Ingress(this, 'web-ingress', {
                metadata: { name: 'web-ingress' },
                spec: {
                  rules: [
                    {
                      host: 'web.local',
                      http: {
                        paths: [
                          {
                            path: '/',
                            backend: {
                              service: {
                                name: 'web-service',
                                port: { number: 80 },
                              },
                            },
                          },
                        ],
                      },
                    },
                  ],
                },
              });
            }
          }

          const app = new App();
          new MyChart(app, 'my-chart');
          app.synth();
          EOF

          # Compile TypeScript to JavaScript
          npx tsc

          # Create cdk8s.yaml to point to the compiled file
          cat <<EOF > cdk8s.yaml
          app: node dist/main.js
          language: typescript
          EOF

          # Synthesize Kubernetes manifests
          cdk8s synth --output temp-synth-output

          # Ensure the output directory exists before attempting to list files
          mkdir -p cdk8s-go-web/temp-synth-output

          # Debug: List files in the temp-synth-output directory
          ls -al cdk8s-go-web/temp-synth-output

      - name: Copy synthesized YAML to Helm chart templates
        run: |
          mkdir -p helm/go-web-app-chart/templates/generated
          cp cdk8s-go-web/temp-synth-output/*.k8s.yaml helm/go-web-app-chart/templates/generated/

      - name: List files in Helm chart templates directory
        run: |
          echo "Listing files in helm/go-web-app-chart/templates/generated/"
          ls -al helm/go-web-app-chart/templates/generated/

      - name: Commit synthesized files to the repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add helm/go-web-app-chart/templates/generated/*.k8s.yaml
          git commit -m "Add synthesized Kubernetes YAML files for Deployment, Service, and Ingress"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
