name: CDK8s Synth to Helm

on:
  push:
    paths:
      - 'go-web-app/cdk8s-go-web/**'
    branches:
      - main

jobs:
  synth-and-copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install CDK8s CLI and Go dependencies
        run: |
          npm install -g cdk8s-cli
          cd go-web-app/cdk8s-go-web
          go mod tidy

      - name: Synthesize Kubernetes manifests
        run: |
          cd go-web-app/cdk8s-go-web
          cdk8s synth --app "go run main.go" --output temp-synth-output

      - name: Copy synthesized YAML to Helm chart templates
        run: |
          mkdir -p helm/go-web-app-chart/templates/generated
          cp go-web-app/cdk8s-go-web/temp-synth-output/*.k8s.yaml helm/go-web-app-chart/templates/generated/
