name: CDK8s Synth to Helm (TypeScript, No Local Setup)

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  synth-and-copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up CDK8s environment, compile, and synth
        run: |
          cd cdk8s-go-web
          npm init -y
          npm install cdk8s constructs typescript cdk8s-plus-25
          npm install -g cdk8s-cli

          # Create TypeScript configuration file
          cat <<EOF > tsconfig.json
          {
            "compilerOptions": {
              "target": "ES2020",
              "module": "CommonJS",
              "strict": true
            },
            "include": ["**/*.ts"]
          }
          EOF

          # Create main.ts with Deployment and Service configuration
          cat <<EOF > main.ts
          import { App, Chart } from 'cdk8s';
          import { Construct } from 'constructs';
          import * as k8s from 'cdk8s-plus-25';

          class MyChart extends Chart {
            constructor(scope: Construct, id: string) {
              super(scope, id);

              // Create Deployment
              const deployment = new k8s.Deployment(this, 'web-deployment', {
                metadata: { name: 'web' },
                containers: [
                  {
                    image: 'nginx',
                    name: 'nginx-container',
                    ports: [{ containerPort: 80 }]
                  }
                ]
              });

              // Create Service
              new k8s.Service(this, 'web-service', {
                metadata: { name: 'web' },
                ports: [{ port: 80, targetPort: 80 }],
                selector: deployment.select
              });
            }
          }

          const app = new App();
          new MyChart(app, 'my-chart');
          app.synth();
          EOF

          # Compile TypeScript to JavaScript (this will generate main.js)
          npx tsc

          # Create cdk8s.yaml for CDK8s configuration
          cat <<EOF > cdk8s.yaml
          app: node main.js
          language: typescript
          EOF

          # Synthesize the Kubernetes YAML files into the specified directory
          cdk8s synth --output ./temp-synth-output

          # List synthesized files for verification
          ls -al ./temp-synth-output

          # Split the generated YAML file into two parts: one for deployment and one for service
          # Extract Deployment and save to deployment.yaml
          grep -E '^(apiVersion|kind: Deployment|metadata:|spec:)' ./temp-synth-output/my-chart.k8s.yaml > ./temp-synth-output/deployment.yaml

          # Extract Service and save to service.yaml
          grep -E '^(apiVersion|kind: Service|metadata:|spec:)' ./temp-synth-output/my-chart.k8s.yaml > ./temp-synth-output/service.yaml

      - name: Commit all files inside cdk8s-go-web directory
        run: |
          # Set up git configuration
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Add the modified files to git (main.ts, cdk8s.yaml, synthesized YAML, etc.)
          git add cdk8s-go-web/main.ts
          git add cdk8s-go-web/cdk8s.yaml
          git add cdk8s-go-web/temp-synth-output/deployment.yaml
          git add cdk8s-go-web/temp-synth-output/service.yaml
          git add cdk8s-go-web/tsconfig.json

          # Commit the changes and push to the repo
          git commit -m "Add synthesized Kubernetes Deployment and Service YAML files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
