name: CI/CD with All Test Types

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Install dependencies
        run: go mod tidy

      - name: Run all tests with verbose output
        run: |
          mkdir -p test-results  # Create a directory to store test results
          go test -v ./integration/api_integration_test.go > test-results/test_output.log || true # Save test output to file
          
      - name: Upload test results as artifacts
        if: always()  # Upload test results even if some tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/test_output.log  # Specify the file or directory to upload

      # Optional: Upload additional logs or other artifacts
      - name: Upload additional logs
        if: always()  # Upload logs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: additional-logs
          path: ./logs/  # Replace with your actual logs directory or file
