name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'


    # Step 6: Run Go tests with detailed output
    - name: Run tests
      run: |
        go mod tidy
        go test -v ./integration/api_integration_test.go

    # Step 7: Upload test results as artifacts (optional)

