name: CI/CD with Different Test Types

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Run Integration Tests
        run: go test -v ./integration_test/...

      # You would add similar steps for other test types as you implement them
      # For example, for End-to-End Tests (if you create an 'e2e' directory):
      # - name: Run End-to-End Tests
      #   run: go test -v ./e2e/...
      #   # You might need to set up an environment for E2E tests here

      # For Smoke Tests (if you create a 'smoke_test' directory):
      # - name: Run Smoke Tests
      #   run: go test -v ./smoke_test/...

      # Performance, Reliability, Security, Contract, and Canary tests often involve
      # separate tools and more complex setup. You would add steps to execute those tools here.
      # Example for tagged performance tests:
      # - name: Run Performance Tests
      #   run: go test -v -tags=performance ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Build Go application
        run: go build -o go-web-app

  # ... (rest of your build, push, and update-helm-chart jobs remain the same) ...
