name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    # Step 3: Cache Go modules
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-

    # Step 4: Install golangci-lint
    - name: Install golangci-lint
      run: |
        curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-linux-amd64.tar.gz | tar -xzv
        sudo mv golangci-lint-1.50.1-linux-amd64/golangci-lint /usr/local/bin/

    # Step 5: Run golangci-lint (Static Code Analysis) with JSON output
    - name: Run golangci-lint (Static Code Analysis)
      run: |
        golangci-lint run --enable=govet,staticcheck --disable=gofmt --out-format=json

    # Step 6: Run Go tests with detailed output
    - name: Run tests
      run: |
        go mod tidy
        go test -v ./integration/api_integration_test.go

    # Step 7: Upload test results as artifacts (optional)

