jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Run All Tests
        run: go test -v ./

      # You can remove the separate "Run Integration Tests" step
      # if all your tests are in the same directory and you want to run them together.

      # If you later decide to move integration tests to a subdirectory,
      # you would then use a separate step like:
      # - name: Run Integration Tests (if in a subdirectory)
      #   run: go test -v ./integration/...
