name: CI/CD with All Test Types

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Run Unit and Integration Tests
        run: go test -v ./all_tests.go

      - name: Run Performance Tests
        run: go test -bench=. ./all_tests.go
        continue-on-error: true

      # ... (rest of your test steps - the -run flags might be unnecessary if all tests are in all_tests.go) ...
