name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Or any other Go version you're using

      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-linux-amd64.tar.gz | tar -xzv
          sudo mv golangci-lint-1.50.1-linux-amd64/golangci-lint /usr/local/bin/
          
      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./integration/api_integration_test.go

      - name: Run golangci-lint (Static Code Analysis)
        run: golangci-lint run --enable=govet,staticcheck --disable=gofmt
