name: CI/CD with All Test Types

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Install dependencies
        run: go mod tidy

      - name: Run all tests with verbose output
        run: |
          go test -v ./integration/api_integration_test.go || true # Ensures all tests are run, even if some fail

      - name: Upload test results as artifacts (Optional)
        if: failure() # Upload results only if some tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results  # You can specify a directory to store the results, or use a direct file if you prefer
